### ISSUE TITLE
rustls

### ISSUE THREAD

**Issue by gitmalong** [ffindelsberger/rustgecko#1]
could you add rustls support via feature flag?

**Comment by ffindelsberger** [comment]
I can look into it, what is the current use case you need rustls for ?

**Comment by ffindelsberger** [comment]
> could you add rustls support via feature flag?

I can look into it, what is the current use case you need rustls for ?

**Comment by gitmalong** [comment]
it allows serving an app with an image that doesn't ship openssl. it is also supposed to be faster.

**Comment by ffindelsberger** [comment]
got it, will try to merge it today or tomorrow

**Comment by gitmalong** [comment]
awesome thx!
