### ISSUE TITLE
please add simple/token_price/{id}

### ISSUE THREAD

**Issue by gitmalong** [ffindelsberger/rustgecko#2]
See https://www.coingecko.com/en/api/documentation

Might it make sense to generate the API client automatically from the swagger json to easily cover all APIs?

**Comment by ffindelsberger** [comment]
will add the endpoint tomorrow, regarding the generating models and co with the swagger documentation i will look into that.

**Comment by gitmalong** [comment]
Thank you. I tried to generate a client from https://www.coingecko.com/api/documentations/v3/swagger.json with https://github.com/OpenAPITools/openapi-generator-cli but it failed with invalid spec...

**Comment by ffindelsberger** [comment]
after running their api spec through a swagger validator it seems there are 4 to 5 structural issues with the file. 
Until they fix this we sadly cant use it for model generation
