### ISSUE TITLE
Rate limit safety?

### ISSUE THREAD

**Issue by gitmalong** [ffindelsberger/rustgecko#3]
What happens when rate limits are hit? Do the function return an error value then?

**Comment by ffindelsberger** [comment]
429 Too Many Request error can be handled like all 4XX and 5XX errors. The Client returns the underlying reqwest::Error Type

See the Section "Error Handling" in the readme
https://crates.io/crates/rustgecko

**Comment by ffindelsberger** [comment]
i added a better error handling example to the doc
